### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by lausan3** [AlgoArchiveExt/algoarchive.org#18]
Five items that I want to do on the landing page:

- [x] Update theme to the new light one on the extension and change the font to a more professional one (for below the header)
- [x] Add a download on chrome store button to the header
- [ ] Make landing page longer by adding a "Why we decided to make this project" section where we talk about the inspiration from LeetHub and what we are thinking about adding.
- [x] (possibly) refactor the "How it works" section into three small card sections and also update some of the images
- [ ] Add links to the footer, including the GitHub, chrome extension, and discord server.

Thoughts? @noravgs @Ewu694

**Comment by Ewu694** [comment]
Sounds good to me, should be pretty quick to implement these features too.
